### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by alec-deason** [peterstuart/engraver#9]
If it is your intention for this to be an open source project, it would be nice to have a license file to clarify that.

I've been playing with this code (which is working very well, by the way) in the context of a project that's currently just for personal use but which I might want to open source in some manner eventually so I'd like to understand what your intentions for this code are so I can plan towards that.

**Comment by peterstuart** [comment]
@alec-deason Done, thank you for prodding me to get around to it 😄.
